# https://github.com/dorny/paths-filter
python:
  - "api/**"
  - "api/**.py"
  - "pyproject.toml"
  - "uv.lock"
  - "api/base/pyproject.toml"
  - "api/base/uv.lock"
  - "**/python_test.yml"
components-changes:
  - "api/base/aiexec/components/**"
starter-projects-changes:
  - "api/base/aiexec/initial_setup/**"
frontend-tests:
  - "web/tests/**"
frontend:
  - "web/**"
  - "**/typescript_test.yml"
  - "**/jest_test.yml"
docs:
  - "docs/**"

# Test categories and their associated paths
starter-projects:
  - "api/base/aiexec/initial_setup/**"
  - "api/base/aiexec/components/**"
  - "api/base/aiexec/services/**"
  - "api/base/aiexec/custom/**"
  - "api/base/aiexec/api/v1/chat.py"
  - "web/src/pages/MainPage/**"
  - "web/src/utils/reactflowUtils.ts"
  - "web/tests/extended/features/**"
  - "api/base/aiexec/custom/**"
  - "api/base/aiexec/graph/**"

components:
  - "web/src/components/**"
  - "web/src/modals/**"
  - "web/src/pages/FlowPage/**"
  - "web/src/shared/**"
  - "web/src/hooks/**"
  - "web/src/CustomNodes/**"
  - "web/src/style/**"
  - "web/src/utils/styleUtils.ts"
  - "web/tests/core/features/**"
  - "web/tests/core/integrations/**"
  - "web/tests/core/regression/**"
  - "web/tests/extended/integrations/**"
  - "web/tests/extended/features/**"
  - "web/tests/extended/regression/**"
  - "api/base/aiexec/custom/**"
  - "api/base/aiexec/schema/**"
  - "api/base/aiexec/graph/**"
  - "api/base/aiexec/utils/**"
  - "api/base/aiexec/custom/**"
  - "api/base/aiexec/components/**"
  - "api/base/aiexec/initial_setup/**"
  - "api/base/aiexec/serialization/**"

workspace:
  - "api/base/aiexec/inputs/**"
  - "web/src/components/core/parameterRenderComponent/**"
  - "web/src/CustomNodes/**"
  - "web/src/modals/**"
  - "web/src/style/**"
  - "web/src/CustomEdges/**"
  - "web/src/utils/reactflowUtils.ts"
  - "web/src/utils/buildUtils.ts"
  - "web/tests/core/features/**"
  - "web/tests/core/unit/**"
  - "web/tests/extended/features/**"
  - "web/tests/core/regression/**"

api:
  - "api/base/aiexec/api/**"
  - "web/src/controllers/**"
  - "web/tests/core/features/**"
  - "web/tests/extended/features/**"
  - "web/tests/extended/regression/**"

database:
  - "api/base/aiexec/services/database/**"
  - "api/base/aiexec/alembic/**"
  - "web/src/controllers/**"
  - "web/tests/core/features/**"
  - "web/tests/extended/features/**"

mainpage:
  - "web/src/pages/MainPage/**"
