"""Revision ID: 24d6adf58108
Revises: 0882f9657f22
Create Date: 2025-09-10 03:24:01.975009

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24d6adf58108"
down_revision: str | None = "0882f9657f22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
