"""

Revision ID: 8889f6b8f484
Revises: 24d6adf58108
Create Date: 2025-09-14 08:17:02.826159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from aiexec.utils import migration


# revision identifiers, used by Alembic.
revision: str = '8889f6b8f484'
down_revision: Union[str, None] = '24d6adf58108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
