# Bandit configuration file
# For more details see: https://bandit.readthedocs.io/en/latest/config.html

# Tests are run against all files in this project.
# Recursively discover all files from the current directory.
# This is the default behavior.
# targets: []

# Tests are included by default, and can be excluded with the "exclude" option,
# which has the same format as the files list.
# By default, no tests are excluded.
# exclude: []

# Run all tests by default
# This is the default behavior.
# tests: []

# Aggregated output by severity level: "low", "medium", "high" or "all"
# Default is "all"
aggregate:
  - "high"
  - "medium"
  - "low"

# Output report format
# Format: ["txt", "json", "csv", "html", "xml", "sarif"]
# Default is "txt"
output_format: "txt"

# Output file (stdout if not specified)
# output_file: ""

# Custom plugins to load
# plugins: []

# Skip these tests
# Example: ["B101", "B404"]
# skip: []

# Only run specific tests
# Example: ["B101", "B404"]
# tests: []

# Custom test configuration
# Example:
# B101:
#   check_import_from: True

# Include one or more test files and paths
# [test_set_1]
# include = []
# exclude = []
# tests = []
# skips = []

# [test_set_2]
# include = []
# exclude = []
# tests = []
# skips = []

# Ignore paths
# Example:
# exclude_dirs: ["tests/*", "docs/*"]

# List of plugins to load
# plugins: []

# List of test IDs to include
# include: []

# List of test IDs to exclude
# exclude: []

# Severity level threshold (low, medium, high, critical)
# severity: "low"

# Confidence level threshold (low, medium, high)
# confidence: "medium"

# Number of lines of context to include in reports
# lines_of_context: 3

# Show the source code with line numbers
# show_code: True

# Show the filename in the output
# show_filename: True

# Output format options
# output_format: "txt"  # txt, json, csv, html, xml, sarif

# Output file (stdout if not specified)
# output_file: ""

# Use color in output
# color: True

# Verbose output
# verbose: 1

# Debug output
# debug: False

# Profile to use for selecting tests
# profile: ""

# Configuration file to use
# config_file: ""

# Path to a directory containing custom plugins
# plugin_path: ""

# List of test IDs to run (takes precedence over profile)
# test_names: []

# List of test IDs to skip
# skip: []

# List of test IDs to run (takes precedence over skip)
# select: []

# Recursively scan directories
# recursive: True

# Follow symlinks
# follow_links: False

# Only show first match per file
# first_match: False

# Show the source code with line numbers
# show_code: True

# Show the filename in the output
# show_filename: True

# Show the line number in the output
# show_lineno: True

# Show the column number in the output
# show_column: True

# Show the severity in the output
# show_severity: True

# Show the confidence in the output
# show_confidence: True

# Show the test ID in the output
# show_test_id: True

# Show the test name in the output
# show_test_name: True

# Show the test message in the output
# show_test_message: True

# Show the test more info in the output
# show_test_more_info: True

# Show the test code in the output
# show_test_code: True

# Show the test filename in the output
# show_test_filename: True

# Show the test line number in the output
# show_test_lineno: True

# Show the test column number in the output
# show_test_column: True

# Show the test severity in the output
# show_test_severity: True

# Show the test confidence in the output
# show_test_confidence: True

# Show the test ID in the output
# show_test_id: True

# Show the test name in the output
# show_test_name: True

# Show the test message in the output
# show_test_message: True

# Show the test more info in the output
# show_test_more_info: True

# Show the test code in the output
# show_test_code: True
